// ISO 3166-1 country names + ISO 4217 primary currency codes for countries
// that appear in the ISO 13616 IBAN registry. Covers all ~80 countries supported
// by ibantools. Currency = the country's primary domestic currency.

export type CountryInfo = { name: string; currency: string }

export const COUNTRIES: Record<string, CountryInfo> = {
  AD: { name: 'Andorra', currency: 'EUR' },
  AE: { name: 'United Arab Emirates', currency: 'AED' },
  AL: { name: 'Albania', currency: 'ALL' },
  AO: { name: 'Angola', currency: 'AOA' },
  AT: { name: 'Austria', currency: 'EUR' },
  AZ: { name: 'Azerbaijan', currency: 'AZN' },
  BA: { name: 'Bosnia and Herzegovina', currency: 'BAM' },
  BE: { name: 'Belgium', currency: 'EUR' },
  BF: { name: 'Burkina Faso', currency: 'XOF' },
  BG: { name: 'Bulgaria', currency: 'BGN' },
  BH: { name: 'Bahrain', currency: 'BHD' },
  BI: { name: 'Burundi', currency: 'BIF' },
  BJ: { name: 'Benin', currency: 'XOF' },
  BR: { name: 'Brazil', currency: 'BRL' },
  BY: { name: 'Belarus', currency: 'BYN' },
  CF: { name: 'Central African Republic', currency: 'XAF' },
  CG: { name: 'Republic of the Congo', currency: 'XAF' },
  CH: { name: 'Switzerland', currency: 'CHF' },
  CI: { name: "Côte d'Ivoire", currency: 'XOF' },
  CM: { name: 'Cameroon', currency: 'XAF' },
  CR: { name: 'Costa Rica', currency: 'CRC' },
  CV: { name: 'Cabo Verde', currency: 'CVE' },
  CY: { name: 'Cyprus', currency: 'EUR' },
  CZ: { name: 'Czech Republic', currency: 'CZK' },
  DE: { name: 'Germany', currency: 'EUR' },
  DJ: { name: 'Djibouti', currency: 'DJF' },
  DK: { name: 'Denmark', currency: 'DKK' },
  DO: { name: 'Dominican Republic', currency: 'DOP' },
  DZ: { name: 'Algeria', currency: 'DZD' },
  EE: { name: 'Estonia', currency: 'EUR' },
  EG: { name: 'Egypt', currency: 'EGP' },
  ES: { name: 'Spain', currency: 'EUR' },
  FI: { name: 'Finland', currency: 'EUR' },
  FK: { name: 'Falkland Islands', currency: 'FKP' },
  FO: { name: 'Faroe Islands', currency: 'DKK' },
  FR: { name: 'France', currency: 'EUR' },
  GA: { name: 'Gabon', currency: 'XAF' },
  GB: { name: 'United Kingdom', currency: 'GBP' },
  GE: { name: 'Georgia', currency: 'GEL' },
  GI: { name: 'Gibraltar', currency: 'GIP' },
  GL: { name: 'Greenland', currency: 'DKK' },
  GQ: { name: 'Equatorial Guinea', currency: 'XAF' },
  GR: { name: 'Greece', currency: 'EUR' },
  GT: { name: 'Guatemala', currency: 'GTQ' },
  GW: { name: 'Guinea-Bissau', currency: 'XOF' },
  HN: { name: 'Honduras', currency: 'HNL' },
  HR: { name: 'Croatia', currency: 'EUR' },
  HU: { name: 'Hungary', currency: 'HUF' },
  IE: { name: 'Ireland', currency: 'EUR' },
  IL: { name: 'Israel', currency: 'ILS' },
  IQ: { name: 'Iraq', currency: 'IQD' },
  IR: { name: 'Iran', currency: 'IRR' },
  IS: { name: 'Iceland', currency: 'ISK' },
  IT: { name: 'Italy', currency: 'EUR' },
  JO: { name: 'Jordan', currency: 'JOD' },
  KM: { name: 'Comoros', currency: 'KMF' },
  KW: { name: 'Kuwait', currency: 'KWD' },
  KZ: { name: 'Kazakhstan', currency: 'KZT' },
  LB: { name: 'Lebanon', currency: 'LBP' },
  LC: { name: 'Saint Lucia', currency: 'XCD' },
  LI: { name: 'Liechtenstein', currency: 'CHF' },
  LT: { name: 'Lithuania', currency: 'EUR' },
  LU: { name: 'Luxembourg', currency: 'EUR' },
  LV: { name: 'Latvia', currency: 'EUR' },
  LY: { name: 'Libya', currency: 'LYD' },
  MA: { name: 'Morocco', currency: 'MAD' },
  MC: { name: 'Monaco', currency: 'EUR' },
  MD: { name: 'Moldova', currency: 'MDL' },
  ME: { name: 'Montenegro', currency: 'EUR' },
  MG: { name: 'Madagascar', currency: 'MGA' },
  MK: { name: 'North Macedonia', currency: 'MKD' },
  ML: { name: 'Mali', currency: 'XOF' },
  MN: { name: 'Mongolia', currency: 'MNT' },
  MR: { name: 'Mauritania', currency: 'MRU' },
  MT: { name: 'Malta', currency: 'EUR' },
  MU: { name: 'Mauritius', currency: 'MUR' },
  MZ: { name: 'Mozambique', currency: 'MZN' },
  NE: { name: 'Niger', currency: 'XOF' },
  NI: { name: 'Nicaragua', currency: 'NIO' },
  NL: { name: 'Netherlands', currency: 'EUR' },
  NO: { name: 'Norway', currency: 'NOK' },
  OM: { name: 'Oman', currency: 'OMR' },
  PK: { name: 'Pakistan', currency: 'PKR' },
  PL: { name: 'Poland', currency: 'PLN' },
  PS: { name: 'Palestine', currency: 'ILS' },
  PT: { name: 'Portugal', currency: 'EUR' },
  QA: { name: 'Qatar', currency: 'QAR' },
  RO: { name: 'Romania', currency: 'RON' },
  RS: { name: 'Serbia', currency: 'RSD' },
  RU: { name: 'Russia', currency: 'RUB' },
  SA: { name: 'Saudi Arabia', currency: 'SAR' },
  SC: { name: 'Seychelles', currency: 'SCR' },
  SD: { name: 'Sudan', currency: 'SDG' },
  SE: { name: 'Sweden', currency: 'SEK' },
  SI: { name: 'Slovenia', currency: 'EUR' },
  SK: { name: 'Slovakia', currency: 'EUR' },
  SM: { name: 'San Marino', currency: 'EUR' },
  SN: { name: 'Senegal', currency: 'XOF' },
  SO: { name: 'Somalia', currency: 'SOS' },
  ST: { name: 'São Tomé and Príncipe', currency: 'STN' },
  SV: { name: 'El Salvador', currency: 'USD' },
  TD: { name: 'Chad', currency: 'XAF' },
  TG: { name: 'Togo', currency: 'XOF' },
  TL: { name: 'Timor-Leste', currency: 'USD' },
  TN: { name: 'Tunisia', currency: 'TND' },
  TR: { name: 'Turkey', currency: 'TRY' },
  UA: { name: 'Ukraine', currency: 'UAH' },
  VA: { name: 'Vatican City', currency: 'EUR' },
  VG: { name: 'British Virgin Islands', currency: 'USD' },
  XK: { name: 'Kosovo', currency: 'EUR' },
  YE: { name: 'Yemen', currency: 'YER' },
}
